services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat


  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db-pg
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/ewm-stats:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=statistics
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - STATS_SERVICE_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main


  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db-pg
    ports:
      - "6432:5432"
    volumes:
      - ./volumes/postgres/ewm-main:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
